name: CD
on:
  push:
    tags:
      - '*'

jobs:
  deploy-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      # Set version to use in the Docker tags
      - name: Set version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      # Login to DockerHub Registry
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Build the Docker image for the 3 platforms (amd64, arm64, arm/v7)
      - name: Build and push Docker image for 3 platforms
        run: |
          docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 \
            --tag ${{ secrets.DOCKERHUB_USERNAME }}/examples-crolang-p2p-authentication-extension:latest \
            --tag ${{ secrets.DOCKERHUB_USERNAME }}/examples-crolang-p2p-authentication-extension:${{ env.RELEASE_VERSION }} \
            --push .

      # Optionally, clean up and logout
      - name: Logout from DockerHub
        run: docker logout
